# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-a799fc8a-fdf9-41db-901a-47605b883a14";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-a799fc8a-fdf9-41db-901a-47605b883a14".device = "/dev/disk/by-uuid/a799fc8a-fdf9-41db-901a-47605b883a14";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5925-8696";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-1f448602-b4ea-4d88-b633-91ac11646e8f";}
  ];

  powerManagement = {
    enable = true;
    powertop.enable = true;
  };
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
